import Head from 'next/head'
import Image from 'next/image'
import Header from '../Components/Header'
import Navbar from '../Components/Navbar'
import Results from '../Components/Results'
import requests from '../Utils/requests'


export default function Home({results}) {
  // console.log(props); 
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Navbar/>
      <Results results = {results}/>

      
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).
  then(res=>res.json());
  return{
    props:{
      results:request.results,
    },
  };
}